version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: ${BUILD_TARGET}
    volumes:
      - ./api:/go/src/github.com/laster18/1chan/api
      - vendor:/go/src/github.com/laster18/1chan/api/vendor
    ports:
      - 3001:3001
    depends_on:
      - db
    tty:
      true
    environment:
      # tcp:localhost:3306*[db_name]/[user_name]/[password]
      DB_URL: tcp:db:3306*1chan/root/password
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: 1chan
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      target: ${BUILD_TARGET}
    volumes:
      - ./front/:/app:delegated
      - node_modules:/app/node_modules
      # - next:/app/.next
    ports:
      - "3000:3000"
    depends_on:
      - api
  db:
    restart: always
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: 1chan
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - api
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  vendor:
    driver: local
  db:
    driver: local
  node_modules:
    driver: local
  next:
    driver: local
